This file dont have to be executed, it exist only for explaining how i achieved the file "kills.csv"<br>
The file "session.csv" is required
# Library

In [12]:
## Pandas for reading 
import pandas as pd
## Clear Output
from IPython.display import clear_output
## For transforming millisecond to date
from datetime import datetime

# DataSet

In [29]:
### Our DataSet
## We are going to use the light version that has some modification. Set the value to "False"
## For loading the file from plan_kills and elaborating it.
## Else we are going to use the file that is arleady been elaborated
if True:
    kill_db = pd.read_pickle("../data/ufficial/pickle/kills.pkl")
else:
    kill_db = pd.read_csv("../data/server/plan_kills.csv", index_col = "id")
    ## Removing the column "server_uuid"
    kill_db.drop(columns = ["server_uuid"], inplace = True)
    date = []
    for i in range(kill_db.__len__()):
        ## Transforming ms time to human
        date.append(pd.Timestamp(datetime.fromtimestamp((kill_db.iloc[i].date/1000.0).astype(int))))
    ## Replacing
    kill_db.date = date
    ## Saving
    kill_db.to_csv("../data/ufficial/csv/kills.csv")
    kill_db.to_pickle("../data/ufficial/pickle/kills.pkl")

# Analyze

## Dictionary
Lets count every kill - death and what weapon was used.

In [23]:
## First of all, we have to create our dictionary that will contains every value we want.
## Count every killer
killer = {uuid : kills for uuid, kills in kill_db["killer_uuid"].value_counts().iteritems()}
## Count every victim
victim = {uuid : death for uuid, death in kill_db["victim_uuid"].value_counts().iteritems()}
## Before doing for every item, we have to replace "air" with "hand"
kill_db.weapon = kill_db.weapon.replace("Air", "Hand")
weapon = {weapon : kill for weapon, kill in kill_db["weapon"].value_counts().iteritems()}

## Location
Since we dont have any coordinates, we cannot say the excact location.<br>
But, instead of the coordinates, we have the uuid and the session_id.<br>
With the file "session.pkl", we maybe can find the location where the guy died<br>
(i know it's not where the guy is died but where the guy joined)

### Variable

In [30]:
session = pd.read_pickle("../data/ufficial/pickle/session.pkl")

In [39]:
session[session.x_join >= 0]

,uuid,session_start,time,mob_kills,deaths,afk_time,x_join,x_left,y_join,y_left,z_join,z_left
1,b751b9ef-2b6f-4678-9908-718bf93d7089,2020-02-07 22:11:54,25620.0,0.0,0.0,0.0,32,32,73,73,1,1
2,b751b9ef-2b6f-4678-9908-718bf93d7089,2020-02-07 22:12:21,3690.0,0.0,0.0,0.0,32,32,73,73,1,1
3,b751b9ef-2b6f-4678-9908-718bf93d7089,2020-02-07 22:51:01,3124.0,0.0,0.0,0.0,32,32,73,73,1,1
4,f2b5fb77-1b63-422d-851f-c3bbd6b0c418,2020-02-07 23:43:34,5205.0,0.0,0.0,0.0,24,22,70,69,126,127
6,74867f34-c6aa-482b-b611-e3400ed366a6,2020-02-07 23:45:40,78946.0,0.0,1.0,0.0,62,-48,64,72,-200,175
...,...,...,...,...,...,...,...,...,...,...,...,...
493183,4d93ccc7-491e-3f1e-9014-19431906f773,2020-04-14 01:48:40,166910.0,0.0,0.0,0.0,484,512,64,65,-48,0
493184,b751b9ef-2b6f-4678-9908-718bf93d7089,2020-04-14 00:47:16,3891453.0,0.0,1.0,0.0,4,-993554,84,55,0,8.31974e+06
493187,c20222ac-1cfc-32c8-b34e-cc89e2558b95,2020-04-14 01:58:03,5730.0,0.0,0.0,0.0,133,133,63,44,-8,-8
493190,d2f75306-b2fa-42a5-96e4-0bc5e9bef4bd,2020-04-14 02:00:17,39768.0,0.0,0.0,0.0,2936,24,68,45,513,36
493193,03003300-e1d2-4830-ade5-fc6514098166,2020-04-14 02:00:09,82858.0,0.0,0.0,0.0,69666,16,72,62,69310,46

In [41]:
kill_db.loc[10:20]

,killer_uuid,victim_uuid,weapon,date,session_id
id,,,,,
10,b02f2672-fbb6-45ec-8e75-b704c04ad4a1,28f72444-e6db-4df3-8802-90d498a85d24,Air,2020-02-07 23:58:55,106
11,425a0736-686e-4432-bec8-f78a47051fec,7bdb37d4-9675-426f-a4da-5eed9a8f82f6,Wood Pickaxe,2020-02-07 23:57:08,113
12,95786fc5-4063-439b-b663-c9b62dffb7b6,55d5ffc4-51d7-4907-91f9-bdcea629e43c,Air,2020-02-07 23:54:30,116
13,085f45de-5661-44e6-a504-5f450d335ff3,f2b5fb77-1b63-422d-851f-c3bbd6b0c418,Wood Sword,2020-02-07 23:55:46,121
14,085f45de-5661-44e6-a504-5f450d335ff3,4a5d6a59-3034-4898-a4e4-f519e2c7b3c0,Wood Sword,2020-02-07 23:56:14,121
15,b02f2672-fbb6-45ec-8e75-b704c04ad4a1,66547d8e-13bd-4d76-b9c3-a910dfdd9b31,Wood Sword,2020-02-08 00:00:10,125
16,16fc0845-d6dd-43b3-8d18-e62a97f5834f,cc19f6d3-e735-49a6-a752-5262f6518dc4,Wood Sword,2020-02-07 23:59:49,141
17,6a37e2aa-6810-4468-b99e-def99b77351b,f005c92e-fa6e-49c5-8566-358405d659c0,Air,2020-02-08 00:00:54,143
18,66547d8e-13bd-4d76-b9c3-a910dfdd9b31,bd0dd2a6-d1d5-4d07-809e-625c14f04cee,Air,2020-02-08 00:00:08,148
19,aa34927a-760f-44df-9ac1-0b911c8ce724,b51f37f8-22ac-4ebe-b012-9855d3a69505,Air,2020-02-08 00:01:27,149
20,7ec79f2e-f4c7-4fbd-8f02-843c6c386f49,1f4044f0-b781-4c99-ab74-6d33407e7aec,Wood Sword,2020-02-08 00:01:44,187